name: Daily Terraform Deployment

on:
  schedule:
    - cron: '00 6 * * *' # 使用 UTC 时间，这里 18 点对应中国时间的 2 点,先在一点进行测试
    - cron: '30 6 * * *' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: dailyTest # 切换到 dailyTest 分支

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.4 

      - name: Initialize Terraform
        env:
          TF_VAR_access_key: ${{ secrets.ALI_ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.ALI_SECRET_KEY }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_user_name: ${{ secrets.GITHUB_USERNAME }}
          TF_VAR_user_email: ${{ secrets.GITHUB_EMAIL }}
        run: terraform -chdir=./Terraform/Aliyun init

      - name: Apply Terraform Configuration
        env:
          TF_VAR_access_key: ${{ secrets.ALI_ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.ALI_SECRET_KEY }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_user_name: ${{ secrets.GITHUB_USERNAME }}
          TF_VAR_user_email: ${{ secrets.GITHUB_EMAIL }}
        run: terraform -chdir=./Terraform/Aliyun apply -auto-approve

  destroy:
    runs-on: ubuntu-latest
    needs: deploy # 确保在 destroy 作业之前先执行 deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: dailyTest # 切换到 dailyTest 分支

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.4 

      - name: Initialize Terraform for Destroy
        env:
          TF_VAR_access_key: ${{ secrets.ALI_ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.ALI_SECRET_KEY }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_user_name: ${{ secrets.GITHUB_USERNAME }}
          TF_VAR_user_email: ${{ secrets.GITHUB_EMAIL }}
        run: terraform init -chdir=./Terraform/Aliyun

      - name: Destroy Terraform Configuration
        env:
          TF_VAR_access_key: ${{ secrets.ALI_ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.ALI_SECRET_KEY }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_user_name: ${{ secrets.GITHUB_USERNAME }}
          TF_VAR_user_email: ${{ secrets.GITHUB_EMAIL }}
        run: terraform -chdir=./Terraform/Aliyun destroy -auto-approve
