name: Test Branch

on:
  push:
    branches: [dailyTest]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check GitHub Secrets
        run: |
          if [ -z "${{ secrets.MYAPP_GITHUB_TOKEN }}" ]; then
            echo "GitHub Token is missing"
          else
            echo "GitHub Token is set"
          fi

          if [ -z "${{ secrets.MYAPP_USER_EMAIL }}" ]; then
            echo "User Email is missing"
          else
            echo "User Email is set"
          fi

          if [ -z "${{ secrets.MYAPP_USER_NAME }}" ]; then
            echo "User Name is missing"
          else
            echo "User Name is set"
          fi

